# Generated by Django 5.1.4 on 2024-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
